site_name: jiphyeonjeon develop documentation
theme: readthedocs
extra:
  static_dirs:
    - doc/image
nav:
  - 홈: index.md
  - 컨벤션: convention.md
  - 이슈 전략: issue_strategy.md
  - 깃 플로우 전략: gitflow.md
  - 에러 코드: error.md